### ISSUE TITLE
Table Rendering Not Working

### ISSUE THREAD

**Issue by crocme10** [basverweij/markdown-it-gridtables#6] opened 2019-10-05 15:15 UTC
Hello,

This might be a fustrating issue, because I can't seem to narrow what triggers the error. 

[test.txt](https://github.com/basverweij/markdown-it-gridtables/files/3693400/test.txt)

The first table is not rendered as a table, but as normal text (so lots of --- and ===)

The link is formatted okay,

And the second table is rendered correctly.

Now, for the weird part.... If, in the gridtable, I replace the first part of the link (which is a folder that exists) by another string (the name of a folder that doesn't exist) then the table is rendered correctly.

Thank you for taking a look

**Comment by basverweij** [comment] 2019-10-06 12:44
Hi,

Thanks for reporting this! Unfortunately, I'm not able to reproduce the problem you described. I've added the example Markdown as a test case (https://github.com/basverweij/markdown-it-gridtables/blob/master/test/gridtable-rule.spec.ts#L58), and it generates the expected HTML correctly: https://github.com/basverweij/markdown-it-gridtables/blob/master/test/test-1.md.html

I did took the opportunity to update the dependencies and publish a new version (v0.2.0).

Could you please try with the latest version, and if it's still not working, provide me with a complete code example?

Thanks!

**Comment by crocme10** [comment] 2019-10-07 10:23
Hello,

I've tried the latest version, and I still have the problem.

I've provided a project for you to try: https://github.com/riendegris/gridtest.

This is a nuxt.js application, where all the markdown stored in the 'assets/content' directory are automatically rendered with a url '/blog/filebasename'.

The rendering occurs in the file 'pages/blog/_post.vue' where I call the global $md renderer.

This global renderer is defined in `plugins/markdown-it.js`, where I import your gridtable plugin.


Steps to reproduce:

1. build and run (`npm run dev`) the project. Check your browser.... The table is not rendered properly.
2. Edit `assets/content/index.md`: in the link, remove the 'a' from 'assets'
3. Edit the rest of the grid table to make sure all the columns are properly aligned.
4. Reload your browser.... Tada! The table is properly rendered.

Thanks for your help and for your plugin!

**Comment by basverweij** [comment] 2019-10-07 19:22
Hi,

Thanks for providing the example project! Using it I was able to reproduce the problem, and also to find the cause.

In the file `store/index.js` the contents of each post is 'pre-processed' ([line 21](https://github.com/riendegris/gridtest/blob/master/store/index.js#L21)), which means that all links to files matching the `assets/content/*.md` pattern are replaced by the file name. This causes the grid table in the resulting Markdown to be invalid (as the column separators do not match up anymore).

For example, the input:

```
+----------------------------------------------------+-----------------------------+
| Project                                            | Task                        |
+====================================================+=============================+
| Does not work: [Discover](assets/content/index.md) | Find a way to apply patches |
+----------------------------------------------------+-----------------------------+
```

Is pre-processed to:

```
+----------------------------------------------------+-----------------------------+
| Project                                            | Task                        |
+====================================================+=============================+
| Does not work: [Discover](index) | Find a way to apply patches |
+----------------------------------------------------+-----------------------------+
```

As you can see, the pre-processed table is no longer valid.

In order to solve this, use the final link in your content:

```
+-------------------------------+-----------------------------+
| Project                       | Task                        |
+===============================+=============================+
| This works: [Discover](index) | Find a way to apply patches |
+-------------------------------+-----------------------------+
```

I'm closing the issue as it is not related to the GridTable MarkdownIt plugin.

**Closed as completed by basverweij** 2019-10-07 19:22 UTC

**Comment by crocme10** [comment] 2019-10-08 08:58
Thank you! Sorry for the trouble.
